config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  #devise_for :users
  devise_for :users, :controllers => { :registrations => :registrations, omniauth_callbacks: 'users/omniauth_callbacks' }

 # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :pages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  resources :user_skills, only: [ :create, :update]

  resources :projects, only: [ :new, :create, :show, :index, :destroy, :edit, :update] do
    resources :jobs, only: [ :create]
    resources :host_reviews, only: [:create]
  end

  resources :jobs, only: [:destroy ] do
    resources :job_reviews, only: [ :create ]
    resources :responses, only: [:create]
  end

  resources :responses, only: [:destroy, :update]

  resources :pages, only: [:show]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :host_reviews
  has_many :jobs
  validates :title, presence: true
  validates :description, presence: true
  validates :schedule, presence: true
  validates :location, presence: true




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def index
    params[:search] ||= {}
    #@projects_by_subject = []

    # if params[:search]
    #   @projects = Project.where(nil)
    #   @projects = projects.where(schedule: params[:search][:schedule]) if params[:search][:schedule]
    #   @projects = projects.where(schedule: params[:search][:schedule]) if params[:search][:schedule]
    #   @projects = projects.where(schedule: params[:search][:schedule]) if params[:search][:schedule]
    #   @projects.all

    # if params[:search] && !params[:search][:skill_id].empty?
    #   @skill = Skill.find(params[:search][:skill_id])

    #   @projects = Project.search(params[:search]).order("created_at DESC")

    #   # Job.create(project_id: @projects.first.id, skill_id: @skill.id)
    #   @projects.each do |project|
    #     @projects_by_subject << project.jobs.where(skill_id: @skill.id)
    #   end

    #   @projects_by_subject.flatten!

    @jobs = Job.search(params[:search]).order('created_at DESC')
  end

  def show
    @project = Project.find(params[:id])
    @job = Job.new
    @job_review = JobReview.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      render 'projects/new'
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :schedule, :location)
  end

  def skill_params
    params.require(:skill).permit(:title)
  end
end

app/views/projects/_form_for_jobreview.html.erb
<% if job.job_review %>
  <% review = job.job_review %>
    <div class="review">
      <p><% review.rating.times do %><i style="color: #e5d200;" class="fa fa-star" aria-hidden="true"></i><% end %></p>
      <p><%= review.content %></p>
    </div>
  <% end %>
<% else %>
  <%= simple_form_for [job, @job_review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: [1,2,3,4,5] %>
     <%= f.submit "Add a review", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/projects/_project.html.erb
<% projects_by_subject.each do |project_by_subject| %>
	<div class="boxx" style="position: relative; display:flex-center;">
	    <div class="col-xs-12 col-sm-4">
		    	<%= link_to project_path(project_by_subject.project) do %>
		    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.mormontransitions.org/wp-content/uploads/2015/12/Movie-making4.jpg');">
		  		<div class="card-category"><%= project_by_subject.project.location %></div>
		  			<div class="card-description">
		    			<h2><%= project_by_subject.project.title %></h2>
		    			<p><%= project_by_subject.project.schedule %></p>
		    		</div>
		    	<!-- <img class="card-user" src="https://placehold.it/300x300.png"> -->
          <%= cl_image_tag user_avatar(project_by_subject.project.user), crop: :fill, class: "card-user" %>
			</div>
			<div class="card-footer">
        		<h3><%= project_by_subject.skill.title %></h3>
        	</div>
		<% end %>
		</div>
	</div>
<% end %>

app/views/projects/index.html.erb
<div class="container">
<h1 class="text-center" >Jobs</h1>
	<div class="container_searchbar col-xs-12">
		<div class="form-group">
		<%= form_tag(projects_path, method: :get, id: "search-form") do %>
			<div class="col-xs-3 container_searchfield">
			<label for="container_searchfield">Where</label>
				<%= text_field_tag :search, value = "", name: "search[location]" , placeholder: "Anywhere", class: "form-control" %>
			</div>
		        <div class="col-xs-3 date">
		           	<label for="date">When</label>
		            <div class="input-group input-append date" id="datePicker">
		                <%= text_field_tag "search[schedule]", {}, placeholder: "Anytime", value: params[:search][:schedule], class: "form-control" %>
		                <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
		            </div>
		        </div>

			<div class="col-xs-3">
		    <label for="searchbar_dropdown">Role</label>
				<%= collection_select(:search, :skill_id, Skill.all.order("title ASC"), :id, :title, {:prompt => ""}, class: "form-control" ) %>
		  	</div>

			<div class="col-xs-3" id="search_button">
				<%= submit_tag "Dig for projects", name: nil, class: 'btn btn-primary' %>
				<% end 	%>
		    </div>
		</div>
	</div>

<% if @jobs.any? %>

		<%= render "project" , projects_by_subject: @jobs %>

<% else %>
	<p>There are no projects containing the term(s) <%= params[:search] %></p>
<% end %>
</div>


<%= content_for :after_js do %>
	<script>
	$('#datePicker').datepicker({
	        autoclose: true,    // It is false, by default
	        format: 'dd/mm/yyyy'
	    }).on('changeDate', function(e) {

	    });
	</script>

	<script>
	$(document).ready(function() {
	    $('#datePicker')
	        .datepicker({
	            autoclose: true,
	            format: 'dd/mm/yyyy'
	        })
	        .on('changeDate', function(e) {
	            // Revalidate the date field
	            $('#eventForm').formValidation('revalidateField', 'date');
	        });

	    });
	</script>
<% end %>

app/views/projects/new.html.erb
<div class="container container-form">
  <div class="row">
    <div class="col-xs-12">
      <h1>New Project</h1>
    </div>
  </div>
  <hr>
  <%= simple_form_for @project do |f| %>
    <div class="row">
      <div class="col-xs-12 center-text">
        <%=f.input :title, :input_html => {:placeholder => "Enter title here"}, :label => "Title" %>
      </div>
      </div>
      <div class="row">
        <div class="col-xs-12 center-text">
          <%=f.input :description, :input_html => {:placeholder => "Describe your project"}, :label => "Description" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <%=f.input :schedule %>
        </div>
        <div class="col-xs-6">
          <%=f.input :location, :input_html => {:placeholder => "City"}, :label => "Location" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4">
        </div>
        <div class="col-xs-4">
          <%= f.submit "Burrow Project", class: 'button btn btn-primary' %>
        </div>
        <div class="col-xs-4">
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container ">
<div class="row">
<div class="col-xs-12">
  <div class="text-center title ">
    <h1>  <%= link_to '<i class="fa fa-arrow-left" aria-hidden="true"></i>'.html_safe, projects_path %></h1>
    <h1>  <%= @project.title.capitalize %></h1>
    <h1 style="color: gold;margin-right: 10px;"><i class="fa fa-trophy" aria-hidden="true"></i></h1>
  </div>
  </div>
</div>
  <div class="row">
    <div class="col-xs-4">
      <div class="description">
      <h3>Info</h3>
        <h4><%= @project.location %></h4>
        <h4><%= @project.schedule %></h4>
      </div>
    </div>
      <div class="col-xs-8">
        <div class="description">
        <h3>Description</h3>
          <p><%= @project.description %><p>
        </div>
      </div>
  </div>

<div class="description">
  <div class="form">
  <h3>Add job <i class="fa fa-plus" aria-hidden="true"></i></h3>
  <% if current_user == @project.user %>
    <%= simple_form_for [@project, @job] do |f| %>
      <%=f.input :skill_id , collection: Skill.all  %>
      <%= f.submit "Add job", class: 'btn btn-primary' %>
    <% end %>
  <% end %>
  </div>
    <% @project.jobs.each do |job| %>
     <div class="list-group ">
      <li class='list-group-item'>
      <% skill = Skill.find(job.skill_id) %>

        <h4 class="list-group-item-heading"> <%= skill.title %>
        <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, job_path(job), class: 'btn btn-danger del ' , method: :delete, data: { confirm: 'Are you certain you want to delete this?' } if current_user == @project.user %></h4>
          <%if current_user == @project.user %>
                <% job.responses.each do |response|%>
                <%= response.user.first_name %>
                <% if response.status == "pending" %>
                  <%= simple_form_for [response] do |f| %>
                    <%= f.input :status, :as => :hidden, :input_html => { :value => "accepted" } %>
                    <%= f.submit "accept", class: "btn btn-success" %>
                  <% end %>
                <%= simple_form_for [response] do |f| %>
                  <%= f.input :status, :as => :hidden, :input_html => { :value => "denied" } %>
                  <%= f.submit "reject", class: "btn btn-danger" %>
                <% end %>
                <% else %>
                  <p><%= response.status.capitalize %></p>
                  <% if response.status == "accepted" %>

                    <% if job.job_review %>
                      <% review = job.job_review %>
                      <div class="review">
                        <p><% review.rating.times do %><i style="color: #e5d200;" class="fa fa-star" aria-hidden="true"></i><% end %></p>
                        <p><%= review.content %></p>
                      </div>
                    <% else %>
                      <%= simple_form_for [job, @job_review] do |f| %>
                        <%= f.input :content %>
                        <%= f.input :rating, collection: [1,2,3,4,5] %>
                        <%= f.submit "Add a review", class: "btn btn-primary" %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>

          <% end %>

      <% elsif user_signed_in? %>
          <% if (job.responses & current_user.responses).empty? %>
                <%= simple_form_for [job, Response.new] do |f| %>
                  <%= f.input :status, :as => :hidden, :input_html => { :value => "pending"} %>
                  <%= f.submit "Apply", class: "btn btn-primary" %>
                <% end %>
          <% else %>
            <p class="btn btn-success"><%=  (job.responses & current_user.responses).first.status%> </p>
          <% end %>
          <p> <%= "#{job.responses.count} people applied in total" %></p>

      <% end %>

      </li>
      </div>
  <% end %>
  </div>
</div>