config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  #devise_for :users
  devise_for :users, :controllers => { :registrations => :registrations, omniauth_callbacks: 'users/omniauth_callbacks' }

 # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :pages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  resources :user_skills, only: [ :create, :update]

  resources :projects, only: [ :new, :create, :show, :index, :destroy, :edit, :update] do
    resources :jobs, only: [ :create]
    resources :host_reviews, only: [:create]
  end

  resources :jobs, only: [:destroy ] do
    resources :job_reviews, only: [ :create ]
    resources :responses, only: [:create]
  end

  resources :responses, only: [:destroy, :update]

  resources :pages, only: [:show]
end

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     Moleywood 2017. Property of SlooshCo
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag ("moleywood_maszj1") %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "DONATE", pages_path, class:"btn btn-danger"%>
      <%= link_to "Search", projects_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "New Project", new_project_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

         <%= cl_image_tag user_avatar(current_user), width: 150, height: 150, crop: :fill, class: "avatar dropdown-toggl  e", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Home</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Logout</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>MoleyWood</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="page-wrapper">
      <%= render "layouts/navbar" %>
      <%= render 'layouts/flashes' %>
      <%= yield %>

   </div>


    <%= render "layouts/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
      
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
    <%= yield(:after_js) %>


  </body>
</html>